/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BooksNewRouteImport } from './routes/books/new'
import { Route as BooksSlugRouteImport } from './routes/books/$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiVapiSearchBookRouteImport } from './routes/api/vapi.search-book'

const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksNewRoute = BooksNewRouteImport.update({
  id: '/books/new',
  path: '/books/new',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksSlugRoute = BooksSlugRouteImport.update({
  id: '/books/$slug',
  path: '/books/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVapiSearchBookRoute = ApiVapiSearchBookRouteImport.update({
  id: '/api/vapi/search-book',
  path: '/api/vapi/search-book',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books/new': typeof BooksNewRoute
  '/api/vapi/search-book': typeof ApiVapiSearchBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books/new': typeof BooksNewRoute
  '/api/vapi/search-book': typeof ApiVapiSearchBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/api/upload': typeof ApiUploadRoute
  '/books/$slug': typeof BooksSlugRoute
  '/books/new': typeof BooksNewRoute
  '/api/vapi/search-book': typeof ApiVapiSearchBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscriptions'
    | '/api/upload'
    | '/books/$slug'
    | '/books/new'
    | '/api/vapi/search-book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscriptions'
    | '/api/upload'
    | '/books/$slug'
    | '/books/new'
    | '/api/vapi/search-book'
  id:
    | '__root__'
    | '/'
    | '/subscriptions'
    | '/api/upload'
    | '/books/$slug'
    | '/books/new'
    | '/api/vapi/search-book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  ApiUploadRoute: typeof ApiUploadRoute
  BooksSlugRoute: typeof BooksSlugRoute
  BooksNewRoute: typeof BooksNewRoute
  ApiVapiSearchBookRoute: typeof ApiVapiSearchBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/new': {
      id: '/books/new'
      path: '/books/new'
      fullPath: '/books/new'
      preLoaderRoute: typeof BooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$slug': {
      id: '/books/$slug'
      path: '/books/$slug'
      fullPath: '/books/$slug'
      preLoaderRoute: typeof BooksSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vapi/search-book': {
      id: '/api/vapi/search-book'
      path: '/api/vapi/search-book'
      fullPath: '/api/vapi/search-book'
      preLoaderRoute: typeof ApiVapiSearchBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  ApiUploadRoute: ApiUploadRoute,
  BooksSlugRoute: BooksSlugRoute,
  BooksNewRoute: BooksNewRoute,
  ApiVapiSearchBookRoute: ApiVapiSearchBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
